name: Build Module
on: push

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Debug

jobs:
    build_linux_latest:
        runs-on: ubuntu-latest
        steps:
        - name: Repo checkout
          uses: actions/checkout@v4
        - name: Get SDR++ nightly source
          run: 'wget https://github.com/AlexandreRouma/SDRPlusPlus/archive/refs/tags/nightly.tar.gz && pwd && ls -lah'
        - name: Get SDR++ nightly lib
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            repo: 'AlexandreRouma/SDRPlusPlus'
            version: 'tags/nightly'
            file: 'sdrpp_debian_sid_amd64.deb'
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Unpack SDR++ source and core lib
          run: 'mkdir sdrpp_lib && tar -zxvf nightly.tar.gz -C sdrpp_lib && dpkg-deb -xv sdrpp_debian_sid_amd64.deb ./sdrpp_lib && cp ./.github/workflows/sdrpp_module_hack.cmake ./ && pwd && ls -lah && ls -lah sdrpp_lib'
        - name: Download libosmocore
          working-directory: ./libosmocore
          run: 'git clone git@github.com:osmocom/libosmocore.git'
        - name: Build libosmocore
          run: 'cd libosmocore && ./configure && make -j4'
        - name: Cmake
          run: 'mkdir build && cd build && ls -lah .. && cmake .. -DSDRPP_MODULE_CMAKE="$GITHUB_WORKSPACE/sdrpp_module_hack.cmake"'
        - name: Download ETSI codec
          run: 'cd src/decoder/etsi_codec-patches && ./download_and_patch.sh'
        - name: Make
          run: 'cd build && make -j4'
        - name: Upload library
          uses: actions/upload-artifact@v4
          with:
              name: tetra_demodulator
              path: ./tetra_demodulator.so
